apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: youremail@163.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: 
        dnsNames:
        - '*.yourdomain.com'
      dns01:
        webhook:
          config:
            accessKeyId:
              key: accessKeySecret
              name: alidns-credentials
            accessKeySecretRef:
              key: accessKeySecret
              name: alidns-credentials
            regionId: "cn-shenzhen"
            ttl: 600
          groupName: certmanager.webhook.alidns
          solverName: alidns
